language: go
go: 1.12.x
env:
  - GO111MODULE=on

script: make

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    branch: master
    tags: true
